// ─── Application Constants ─────────────────────────────────

export const API_PREFIX = "/api/v1";

export const PAGINATION = {
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 10,
  MAX_LIMIT: 100,
} as const;

export const ASSET_TAG_PREFIX = "AF";
export const ASSET_TAG_PAD_LENGTH = 4;

export const ASSET_CONDITIONS = ["Good", "Fair", "Poor"] as const;

export const NOTIFICATION_TYPES = {
  ASSET_ASSIGNED: "ASSET_ASSIGNED",
  MAINTENANCE_APPROVED: "MAINTENANCE_APPROVED",
  MAINTENANCE_REJECTED: "MAINTENANCE_REJECTED",
  BOOKING_CONFIRMED: "BOOKING_CONFIRMED",
  BOOKING_CANCELLED: "BOOKING_CANCELLED",
  BOOKING_REMINDER: "BOOKING_REMINDER",
  TRANSFER_APPROVED: "TRANSFER_APPROVED",
  OVERDUE_RETURN: "OVERDUE_RETURN",
  AUDIT_DISCREPANCY: "AUDIT_DISCREPANCY",
} as const;

export const ACTIVITY_ACTIONS = {
  ASSET_CREATED: "ASSET_CREATED",
  ASSET_UPDATED: "ASSET_UPDATED",
  ASSET_ALLOCATED: "ASSET_ALLOCATED",
  ASSET_RETURNED: "ASSET_RETURNED",
  TRANSFER_REQUESTED: "TRANSFER_REQUESTED",
  TRANSFER_APPROVED: "TRANSFER_APPROVED",
  TRANSFER_REJECTED: "TRANSFER_REJECTED",
  BOOKING_CREATED: "BOOKING_CREATED",
  BOOKING_CANCELLED: "BOOKING_CANCELLED",
  BOOKING_RESCHEDULED: "BOOKING_RESCHEDULED",
  MAINTENANCE_RAISED: "MAINTENANCE_RAISED",
  MAINTENANCE_APPROVED: "MAINTENANCE_APPROVED",
  MAINTENANCE_REJECTED: "MAINTENANCE_REJECTED",
  MAINTENANCE_ASSIGNED: "MAINTENANCE_ASSIGNED",
  MAINTENANCE_RESOLVED: "MAINTENANCE_RESOLVED",
  AUDIT_CREATED: "AUDIT_CREATED",
  AUDIT_CLOSED: "AUDIT_CLOSED",
  USER_ROLE_UPDATED: "USER_ROLE_UPDATED",
  USER_STATUS_UPDATED: "USER_STATUS_UPDATED",
  DEPARTMENT_CREATED: "DEPARTMENT_CREATED",
  DEPARTMENT_UPDATED: "DEPARTMENT_UPDATED",
  DEPARTMENT_STATUS_TOGGLED: "DEPARTMENT_STATUS_TOGGLED",
  CATEGORY_CREATED: "CATEGORY_CREATED",
  CATEGORY_UPDATED: "CATEGORY_UPDATED",
} as const;

export const ENTITY_TYPES = {
  USER: "User",
  ASSET: "Asset",
  ALLOCATION: "Allocation",
  TRANSFER: "Transfer",
  BOOKING: "Booking",
  MAINTENANCE: "Maintenance",
  AUDIT: "Audit",
  DEPARTMENT: "Department",
  CATEGORY: "Category",
} as const;
